POST http://127.0.0.1:3000/esnvios
Content-Type: application/json

{
  "destino": "san juan",
  "email": "sanjuan@gmail.com"
}

###
GET http://127.0.0.1:3000/envios/pendientes
Content-Type: application/json


### colocar id de un envio
PUT http://127.0.0.1:3000/envios/dd878dbc-2626-45fe-8d89-3e96a6cb8eeb/entregado
Content-Type: application/json


### colocar id de un envio
DELETE http://127.0.0.1:3000/envios/7b6a6091-23c5-4616-ab95-cd98b2075d08/cancelado
Content-Type: application/json


###y