AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de envios
Resources:
  Envios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 20
      Events:
        nuevoEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        listaEnvios:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        envioEntregado:
          Type: Api
          Properties:
            Path: /envios/{idEntrega}/entregado
            Method: put
        cancelarEnvio:
          Type: Api
          Properties:
            Path: /envios/{idDelete}/cancelado
            Method: delete